; Ajustes recomendados para producción / Docker
upload_max_filesize = 50M
post_max_size       = 55M
max_execution_time  = 300
memory_limit        = 512M
date.timezone       = America/Santiago
display_errors      = Off
log_errors          = On
